//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Entity
{
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(Name="customer")]
    public partial class Customer
    {
        [DataMember(Name="id")]	
        public int Id { get; set; }
        [DataMember(Name="nombre")]	
        public string Nombre { get; set; }
        [DataMember(Name="apellido")]	
        public string Apellido { get; set; }
    }
}
